#! /usr/bin/python

################################################################################
# flexiWAN SD-WAN software - flexiEdge, flexiManage.
# For more information go to https://flexiwan.com
#
# Copyright (C) 2019  flexiWAN Ltd.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
################################################################################

import json
import re
import traceback
import copy

from fwcfg_database import FwCfgDatabase

import fwglobals
import fwrouter_api
import fwutils


class FwRouterCfg(FwCfgDatabase):
    """This is requests DB class representation.

    :param db_file: SQLite DB file name.
    """
    # def __init__(self, db_file):
    #     """Constructor method
    #     """
    #     # FwCfgDatabase.__init__(self, db_file)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        # The three arguments to `__exit__` describe the exception
        # caused the `with` statement execution to fail. If the `with`
        # statement finishes without an exception being raised, these
        # arguments will be `None`.
        self.finalize()

    def finalize(self):
        """Destructor method
        """
        self.db.close()

    def clean(self):
        """Clean DB

        :returns: None.
        """
        FwCfgDatabase.clean(self)

    def _get_request_key(self, request):
        """Generates uniq key for request out of request name and
        request parameters. To do that uses the get_request_key() function
        that MUST be defined in the correspondent translator file,
        e.g. fwtranslate_add_tunnel.py.

        !IMPORTANT!  keep this function internal! No one should be aware of
                     database implementation. If you feel need to expose this
                     function, please consider to add API to this class
                     that encapsulates the needed functionality!
        """
        req     = request['message']
        params  = request.get('params')

        # add-/remove-/modify-X requests use key function defined for 'add-X'.
        # start-router & stop-router break add-/remove-/modify- convention.
        if req=='start-router' or req=='stop-router':
            src_req = 'start-router'
        else:
            src_req = re.sub(r'^\w+', 'add', req)
        key_module  = fwrouter_api.fwrouter_modules.get(fwrouter_api.fwrouter_translators[src_req]['module'])
        key_func    = getattr(key_module, 'get_request_key')
        return key_func(params)

    def update(self, request, cmd_list=None, executed=False):
        """Save configuration request into DB.
        The 'add-X' configuration requests are stored in DB, the 'remove-X'
        requests are not stored but remove the correspondent 'add-X' requests.

        :param request:     The request received from flexiManage.
        :param cmd_list:    List of commands to be executed in order to fullfil
                            configuration request. The command can invoke VPP API,
                            run Linux shell commands, update internal agent objects,
                            etc. They are generated by generated by translation.
        :param executed:    The 'executed' flag - True if the configuration
                            request was translated and executed, False if it was
                            translated but was not executed.
        :returns: None.
        """
        req     = request['message']
        params  = request.get('params')
        req_key = self._get_request_key(request)

        try:
            if re.match('add-', req) or re.match('start-router', req):
                self.db[req_key] = { 'request' : req , 'params' : params , 'cmd_list' : cmd_list , 'executed' : executed }
            elif re.match('modify-', req):
                entry = self.db[req_key]
                entry.update({'params' : params})
                self.db[req_key] = entry 
            else:
                del self.db[req_key]

        except KeyError:
            pass
        except Exception as e:
            fwglobals.log.error("update(%s) failed: %s, %s" % \
                        (req_key, str(e), str(traceback.format_exc())))
            raise Exception('failed to update request database')

    def get_request_params(self, request):
        req_key = self._get_request_key(request)
        return self.get_params(req_key)

    def get_request_cmd_list(self, request):
        req_key = self._get_request_key(request)
        return self.get_cmd_list(req_key)

    def request_exists(self, request):
        req_key = self._get_request_key(request)        
        return self.exists(req_key)

    def is_same_cfg_item(self, request1, request2):
        """Checks if provided requests stand for the same configuration item.
        """
        req_key1 = self._get_request_key(request1)
        req_key2 = self._get_request_key(request2)
        if req_key1 == req_key2:
            return True
        return False

    def dump(self, types=None, escape=None, full=False, keys=False):
        """Dumps router configuration into list of requests
        """
        if not types:
            types = [
                'start-router',
                'add-interface',
                'add-tunnel',
                'add-route',		# routes should come after tunnels, as they might use them
                'add-dhcp-config',
                'add-application',
                'add-multilink-policy'
            ]

        return FwCfgDatabase.dump(self, types, escape, full, keys)

    def dumps(self, types=None, escape=None, full=False):
        """Dumps router configuration into printable string.

        :param types:  list of types of configuration requests to be dumped, e.g. [ 'add-interface' , 'add-tunnel' ]
        :param escape: list of types of configuration requests that should be escaped while dumping
        :param full:   return requests together with translated commands.
        """
        sections = {                # Use stairway to ensure section order in
                                    # output string created by json.dumps()
                                    #
            'start-router':         "======= START COMMAND =======",
            'add-interface':        "======== INTERFACES ========",
            'add-route':            "========= ROUTES =========",
            'add-tunnel':           "========== TUNNELS ==========",
            'add-dhcp-config':      "=========== DHCP CONFIG ===========",
            'add-application':      "============ APPLICATIONS ============",
            'add-multilink-policy': "============= POLICIES ============="
        }

        cfg = self.dump(types=types, escape=escape, full=full, keys=True)
        return fwutils.dumps_config(cfg, sections, full)

    def get_interfaces(self, type=None, dev_id=None, ip=None):
        interfaces = self.get_requests('add-interface')
        if not type and not dev_id and not ip:
            return interfaces
        result = []
        for params in interfaces:
            if type and not re.match(type, params['type'], re.IGNORECASE):
                continue
            elif dev_id and dev_id != params['dev_id']:
                continue
            elif ip and not re.match(ip, params['addr']):
                continue
            result.append(params)
        return result

    def get_tunnels(self):
        return self.get_requests('add-tunnel')

    def get_tunnel(self, tunnel_id):
        key = 'add-tunnel:%d' % (tunnel_id)
        return self.get_params(key)

    def get_multilink_policy(self):
        return self.get_params('add-multilink-policy')

    def get_applications(self):
        return self.get_params('add-application')

    def get_wan_interface_gw(self, ip):
        import fwutils
        interfaces = self.get_interfaces(type='wan', ip=ip)
        if not interfaces:
            return (None, None)
        dev_id = interfaces[0]['dev_id']
        gw  = interfaces[0].get('gateway')
        # If gateway not exist in interface configuration, use default
        # This is needed when upgrading from version 1.1.52 to 1.2.X
        if not gw:
            tap = fwutils.dev_id_to_tap(dev_id)
            rip, _ = fwutils.get_interface_gateway(tap)
            return dev_id, rip
        else:
            return dev_id, gw

    def get_sync_list(self, requests):
        """Intersects requests provided within 'requests' argument against
        the requests stored in the local database and generates output list that
        can be used for synchronization of router configuration. This output list
        is called sync-list. It includes sequence of 'remove-X', 'modify-X' and
        'add-X' requests that should be applied to device in order to configure
        it with the configuration, reflected in the input list 'requests'.

        :param requests: list of requests that reflects the desired configuration.
                         The requests are in formant of flexiManage<->flexiEdge
                         message: { 'message': 'add-X', 'params': {...}}.

        :returns: synchronization list - list of 'remove-X', 'modify-X' and
                         'add-X' requests that takes device to the desired
                         configuration if applied to the device.
        """

        # Firstly we hack a little bit the input list as follows:
        # build dictionary out of this list where values are list elements
        # (requests) and keys are request keys that local database would use
        # to store these requests. Accidentally these are exactly same keys
        # dumped by fwglobals.g.router_cfg.dump() used below ;)
        #
        input_requests = {}
        for request in copy.deepcopy(requests): # Use deepcopy as we might modify input_requests[key] below
            key = self._get_request_key(request)
            input_requests.update({key:request})

        # Now dump local configuration in order of 'remove-X' list.
        # We will go over dumped requests and filter out requests that present
        # in the input list and that have same parameters. They correspond to
        # configuration items that should be not touched by synchronization.
        # The dumped requests that present in the input list but have different
        # parameters stand for modifications.
        #
        dumped_requests = fwglobals.g.router_cfg.dump(keys=True)
        output_requests = []

        for dumped_request in dumped_requests:
            dumped_key = dumped_request['key']
            if dumped_key in input_requests:
                # The configuration item presents in the input list.
                #
                dumped_params = dumped_request.get('params')
                input_params  = input_requests[dumped_key].get('params')
                if fwutils.compare_request_params(dumped_params, input_params):
                    # The configuration item has exactly same parameters.
                    # It does not require sync, so remove it from input list.
                    #
                    del input_requests[dumped_key]
                else:
                    # The configuration item should be modified.
                    # Rename requests in input list with 'modify-X'.
                    #
                    # At this stage only 'modify-interface' is supported,
                    # so for the rest types of configuration items we add
                    # the correspondent 'remove-X' request with current
                    # parameters to the output list and later in this function
                    # we will add the 'add-X' request from the input list.
                    #
                    if dumped_request['message'] == 'add-interface':
                        input_requests[dumped_key]['message'] = 'modify-interface'
                    else:
                        dumped_request['message'] = dumped_request['message'].replace('add-', 'remove-')
                        output_requests.append(dumped_request)
            else:
                # The configuration item does not present in the input list.
                # So it stands for item to be removed. Add correspondent request
                # to the output list.
                # Ignore 'start-router', 'stop-router', etc as they are not
                # an configuration items.
                #
                if not re.search('(start|stop)-router', dumped_request['message']):
                    dumped_request['message'] = dumped_request['message'].replace('add-', 'remove-')
                    output_requests.append(dumped_request)


        # At this point the input list includes 'add-X' requests that stand
        # for new or for modified configuration items.
        # Just go and add them to the output list 'as-is'.
        #
        output_requests += input_requests.values()

        return output_requests

    def _full_sync(self, sync_list):
        fwglobals.log.debug("_sync_device: start router full sync")

        restart_router = False
        if fwglobals.g.router_api.state_is_started():
            fwglobals.log.debug("_sync_device: restart_router=True")
            restart_router = True
            fwglobals.g.router_api.call({'message': 'stop-router'})

        fwglobals.g.agent_api._reset_device_soft()

        sync_request = {
            'message':   'aggregated',
            'params':    { 'requests': sync_list },
            'internals': { 'dont_revert_on_failure': True }
        }

        reply = fwglobals.g.router_api.call(sync_request)

        if reply['ok'] == 0:
            raise Exception(" _sync_device: router full sync failed: " + str(reply.get('message')))

        if restart_router:
            fwglobals.g.router_api.call({'message': 'start-router'})

        fwglobals.log.debug("_sync_device: router full sync succeeded")

        return True
